DROP DATABASE paymybuddy;

CREATE DATABASE paymybuddy;
USE paymybuddy;

CREATE TABLE user (
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(255) ,
firstname VARCHAR(50),
lastname VARCHAR(50),
account_balance FLOAT
) ;

CREATE TABLE transfer (
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
date DATE,
amount FLOAT,
reason VARCHAR(50),
creditor INTEGER NOT NULL,
debtor INTEGER NOT NULL,
CONSTRAINT FOREIGN KEY(creditor) REFERENCES user(id) ON DELETE CASCADE,
CONSTRAINT FOREIGN KEY(debtor) REFERENCES user(id) ON DELETE CASCADE
) ;

CREATE TABLE contact (
user INTEGER NOT NULL,
friend INTEGER NOT NULL,
primary key (user, friend),
CONSTRAINT FOREIGN KEY(user) REFERENCES user(id) ON DELETE CASCADE,
CONSTRAINT FOREIGN KEY(friend) REFERENCES user(id) ON DELETE CASCADE
) ;

